import { APP_NAME, CONTACT_EMAIL } from "@/lib/brand";

export const metadata = {
  title: "Terms of Service",
  description: `Terms of Service for ${APP_NAME}.`,
};

export default function TermsOfService() {
  return (
    <div style={{ maxWidth: "800px", margin: "0 auto", padding: "60px 24px", fontFamily: "system-ui, sans-serif", color: "#1e293b", lineHeight: 1.7 }}>
      <h1 style={{ fontSize: "32px", fontWeight: 700, marginBottom: "8px" }}>Terms of Service</h1>
      <p style={{ color: "#64748b", marginBottom: "40px" }}>Last updated: July 19, 2026</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>1. About the service.</h2>
      <p>{APP_NAME} is a free tool for learning and practicing business analysis skills. It is provided free and &quot;as is&quot;, without guarantees of availability. By using it, you agree to these terms.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>2. Free service.</h2>
      <p>{APP_NAME} is currently free of charge. There are no paid plans or billing. If paid features are introduced in the future, these terms will be updated first.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>3. Fair-use limits.</h2>
      <p>Daily usage limits apply (currently 10 AI runs per day for signed-in users) and may change at any time.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>4. For learning only — no confidential data.</h2>
      <p>You agree to use {APP_NAME} for practice and learning only, and not to submit confidential, proprietary, or personal information. Anything you submit is at your own risk.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>5. AI-generated content.</h2>
      <p>Feedback, scores, and documents are generated by AI. They are practice material that may contain mistakes, and are not professional advice. Apply your own judgment before using any output in real work.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>6. Your account.</h2>
      <p>You are responsible for your account and for honest use — no bypassing limits or misusing the service. You can delete your account anytime from your profile page.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>7. Changes to the service.</h2>
      <p>Features may be added, changed, or removed at any time.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>8. Questions.</h2>
      <p>For any questions or grievances: <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#0d9488" }}>{CONTACT_EMAIL}</a></p>
    </div>
  );
}
