import { APP_NAME, APP_URL } from "@/lib/brand";

const APP_DOMAIN = new URL(APP_URL).hostname.replace(/^www\./, "");

export const metadata = {
  title: "Terms of Service",
  description: `Terms of Service for ${APP_NAME}.`,
};

export default function TermsOfService() {
  return (
    <div style={{ maxWidth: "800px", margin: "0 auto", padding: "60px 24px", fontFamily: "system-ui, sans-serif", color: "#1e293b", lineHeight: 1.7 }}>
      <h1 style={{ fontSize: "32px", fontWeight: 700, marginBottom: "8px" }}>Terms of Service</h1>
      <p style={{ color: "#64748b", marginBottom: "40px" }}>Last updated: July 2025</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>1. Acceptance of Terms</h2>
      <p>By accessing or using {APP_NAME} at {APP_DOMAIN}, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>2. Description of Service</h2>
      <p>{APP_NAME} is an AI-powered tool that helps Business Analysts generate structured requirements documents including User Stories, Acceptance Criteria, BRD, FRD, Test Scenarios and related documentation from raw business requirements.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>3. Free and Paid Plans</h2>
      <p>{APP_NAME} offers a Free plan with 5 AI generations per month and a Pro plan with unlimited generations at ₹599 per month. Plan details may change with notice to registered users.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>4. User Responsibilities</h2>
      <ul style={{ paddingLeft: "24px", marginTop: "8px" }}>
        <li>You are responsible for the content you input into the tool</li>
        <li>Do not input confidential client data without appropriate authorisation</li>
        <li>Do not attempt to reverse engineer, copy, or redistribute the service</li>
        <li>One account per user — do not share account credentials</li>
      </ul>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>5. AI-Generated Content</h2>
      <p>The documents generated by {APP_NAME} are AI-assisted and should be reviewed by a qualified Business Analyst before use in any professional or production context. We do not guarantee the accuracy or completeness of AI-generated output.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>6. Intellectual Property</h2>
      <p>The {APP_NAME} platform, including its design, code, and content, is owned by {APP_NAME}. The documents you generate using the tool belong to you.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>7. Limitation of Liability</h2>
      <p>{APP_NAME} is provided &quot;as is&quot; without warranties of any kind. We are not liable for any business decisions made based on AI-generated content from this tool.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>8. Termination</h2>
      <p>We reserve the right to suspend or terminate accounts that violate these terms. You may cancel your account at any time by emailing sambeet09m15@gmail.com.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>9. Governing Law</h2>
      <p>These terms are governed by the laws of India. Any disputes shall be subject to the jurisdiction of courts in India.</p>

      <h2 style={{ fontSize: "20px", fontWeight: 600, marginBottom: "12px", marginTop: "32px" }}>10. Contact</h2>
      <p>For questions about these terms: <a href="mailto:sambeet09m15@gmail.com" style={{ color: "#0d9488" }}>sambeet09m15@gmail.com</a></p>
    </div>
  );
}
